pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'clean package java-tomcat-sample/pom.xml'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
    }
}
